import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import {
  ArrowLeft,
  ShieldAlert,
  ShieldCheck,
  Download,
  Trash2,
  Clock,
  Calendar,
  PhoneCall,
  AlertTriangle,
  Info,
  CheckCircle2,
  Share2,
} from 'lucide-react';
import {
  ResponsiveContainer,
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
} from 'recharts';

export const CallDetailsPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const { calls, deleteCall, addToast } = useApp();
  const navigate = useNavigate();

  const [confirmDeleteModal, setConfirmDeleteModal] = useState(false);

  const call = calls.find((c) => c.id === id);

  if (!call) {
    return (
      <div className="p-12 text-center space-y-4 bg-white rounded-3xl border border-slate-200">
        <h3 className="text-xl font-bold text-slate-800">Call Report Not Found</h3>
        <p className="text-xs text-slate-500">
          The requested forensic report has either expired or been deleted.
        </p>
        <button
          onClick={() => navigate('/call-history')}
          className="px-5 py-2.5 rounded-xl bg-slate-900 text-white font-bold text-xs"
        >
          Return to Call History
        </button>
      </div>
    );
  }

  const isHighRisk = call.riskLevel === 'high' || call.riskLevel === 'critical';

  // Timeline data for risk score progression
  const timelineData = call.transcript.map((seg, i) => ({
    time: seg.timestamp,
    score: seg.riskContribution || (seg.isSuspicious ? Math.min(95, (i + 1) * 22) : 10),
  }));

  const handleExportReport = () => {
    const reportText = `
SAFECALL AI - FORENSIC CALL REPORT
=====================================
Call ID: ${call.id}
Date: ${call.date}
Caller: ${call.callerName || 'Unknown'} (${call.callerNumber})
Duration: ${call.duration}
Overall Risk Score: ${call.riskScore}/100 (${call.riskLevel.toUpperCase()})

EXECUTIVE SUMMARY:
${call.summary}

DETECTED MANIPULATION SIGNALS:
${call.manipulationSignals.map((s) => `• [${s.severity.toUpperCase()}] ${s.label}: ${s.description}`).join('\n')}

TRANSCRIPT BREAKDOWN:
${call.transcript.map((t) => `[${t.timestamp}] ${t.speaker}: ${t.text} ${t.isSuspicious ? '--> [SUSPICIOUS]' : ''}`).join('\n')}

RECOMMENDED PROTECTIVE ACTION:
${call.recommendedActions.map((a, i) => `${i + 1}. ${a}`).join('\n')}
=====================================
Generated by SafeCall AI - Real-Time Scam Protection
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SafeCall_Report_${call.id}.txt`;
    link.click();
    URL.revokeObjectURL(url);

    addToast('Report Exported', 'Forensic call summary downloaded to text file.', 'success');
  };

  const handleExportJson = () => {
    const jsonStr = JSON.stringify(call, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SafeCall_Forensic_${call.id}.json`;
    link.click();
    URL.revokeObjectURL(url);

    addToast('JSON Exported', 'Machine-readable forensic call data downloaded.', 'success');
  };

  const handleDelete = async () => {
    await deleteCall(call.id);
    navigate('/call-history');
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      {/* Back Bar & Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <button
          onClick={() => navigate('/call-history')}
          className="inline-flex items-center space-x-2 text-xs font-bold text-slate-600 hover:text-slate-900 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Call Archive</span>
        </button>

        <div className="flex items-center space-x-2.5">
          <button
            id="export-report-txt-btn"
            onClick={handleExportReport}
            className="py-2.5 px-3.5 rounded-xl border border-slate-300 bg-white hover:bg-slate-50 text-slate-700 text-xs font-bold flex items-center space-x-1.5 transition-colors shadow-xs"
            title="Download formatted text report"
          >
            <Download className="w-4 h-4 text-slate-500" />
            <span>Export Text</span>
          </button>

          <button
            id="export-report-json-btn"
            onClick={handleExportJson}
            className="py-2.5 px-3.5 rounded-xl border border-slate-300 bg-white hover:bg-slate-50 text-slate-700 text-xs font-bold flex items-center space-x-1.5 transition-colors shadow-xs"
            title="Download raw JSON forensic data"
          >
            <Download className="w-4 h-4 text-teal-600" />
            <span>Export JSON</span>
          </button>

          <button
            onClick={() => setConfirmDeleteModal(true)}
            className="py-2.5 px-3 rounded-xl border border-red-200 bg-red-50 hover:bg-red-100 text-red-700 text-xs font-bold flex items-center space-x-1.5 transition-colors"
          >
            <Trash2 className="w-4 h-4 text-red-600" />
            <span>Delete</span>
          </button>
        </div>
      </div>

      {/* CALL SUMMARY CARD */}
      <div
        className={`p-6 sm:p-8 rounded-3xl border-2 text-slate-900 shadow-md ${
          isHighRisk
            ? 'bg-red-50/50 border-red-300'
            : 'bg-white border-slate-200'
        }`}
      >
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6 pb-6 border-b border-slate-200/80">
          <div className="space-y-2">
            <div className="flex items-center space-x-2">
              <span
                className={`px-3 py-1 rounded-full text-xs font-extrabold uppercase tracking-wider ${
                  isHighRisk
                    ? 'bg-red-600 text-white'
                    : 'bg-emerald-600 text-white'
                }`}
              >
                {call.riskLevel} Risk • {call.riskScore}/100
              </span>
              {call.isDemo && (
                <span className="text-xs font-mono bg-slate-200 text-slate-700 px-2 py-0.5 rounded">
                  Demo Simulated Record
                </span>
              )}
            </div>
            <h1 className="text-2xl sm:text-3xl font-black text-slate-900">
              {call.callerName || 'Unknown Caller'}
            </h1>
            <div className="flex flex-wrap items-center gap-4 text-xs text-slate-500">
              <span className="font-mono">{call.callerNumber}</span>
              <span>•</span>
              <span className="flex items-center space-x-1">
                <Calendar className="w-3.5 h-3.5" />
                <span>{call.date}</span>
              </span>
              <span>•</span>
              <span className="flex items-center space-x-1">
                <Clock className="w-3.5 h-3.5" />
                <span>Duration: {call.duration}</span>
              </span>
            </div>
          </div>

          {/* Big score indicator */}
          <div className="flex items-center space-x-4 bg-white p-4 rounded-2xl border border-slate-200 shadow-xs shrink-0">
            <div
              className={`w-14 h-14 rounded-2xl flex items-center justify-center font-black text-2xl ${
                isHighRisk
                  ? 'bg-red-100 text-red-700'
                  : 'bg-emerald-100 text-emerald-700'
              }`}
            >
              {call.riskScore}
            </div>
            <div className="text-xs">
              <span className="font-bold text-slate-900 block">AI Threat Score</span>
              <span className="text-slate-500">
                {isHighRisk ? 'Immediate Intervention' : 'Verified Safe'}
              </span>
            </div>
          </div>
        </div>

        {/* Narrative Summary */}
        <div className="pt-6 space-y-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500">
            Forensic Incident Summary
          </h3>
          <p className="text-sm text-slate-700 leading-relaxed font-medium">
            {call.summary}
          </p>
        </div>
      </div>

      {/* RECOMMENDED ACTIONS BOX */}
      <div className="p-6 rounded-2xl bg-teal-50/70 border border-teal-200 space-y-3">
        <div className="flex items-center space-x-2 text-teal-900 font-bold text-sm">
          <CheckCircle2 className="w-5 h-5 text-teal-600 shrink-0" />
          <span>Recommended Protective Guidance for Senior & Family</span>
        </div>
        <div className="space-y-2 text-xs text-slate-700">
          {call.recommendedActions.map((action, i) => (
            <div key={i} className="flex items-start space-x-2">
              <span className="w-4 h-4 rounded-full bg-teal-200 text-teal-800 text-[10px] font-bold flex items-center justify-center shrink-0 mt-0.5">
                {i + 1}
              </span>
              <span className="leading-relaxed">{action}</span>
            </div>
          ))}
        </div>
      </div>

      {/* DETECTED SIGNALS BREAKDOWN */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 space-y-4">
        <h3 className="font-bold text-slate-900 text-base">
          Detected Social Engineering Patterns ({call.manipulationSignals.length})
        </h3>

        {call.manipulationSignals.length === 0 ? (
          <div className="p-5 bg-emerald-50 rounded-xl text-xs text-emerald-900 flex items-center space-x-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
            <span>Zero deceptive signals detected. Caller operated within verified security guidelines.</span>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {call.manipulationSignals.map((sig) => (
              <div
                key={sig.id}
                className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2"
              >
                <div className="flex items-center justify-between">
                  <span className="font-bold text-slate-900 text-sm">{sig.label}</span>
                  <span
                    className={`text-[10px] font-extrabold uppercase px-2 py-0.5 rounded ${
                      sig.severity === 'critical'
                        ? 'bg-red-100 text-red-800'
                        : 'bg-amber-100 text-amber-800'
                    }`}
                  >
                    {sig.severity}
                  </span>
                </div>
                <p className="text-xs text-slate-600 leading-relaxed">{sig.description}</p>
                {sig.evidenceSnippet && (
                  <div className="p-2 rounded-lg bg-red-100/60 text-red-900 text-[11px] font-mono leading-tight">
                    Evidence: {sig.evidenceSnippet}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* RISK SCORE PROGRESSION TIMELINE */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="font-bold text-slate-900 text-base">Conversational Risk Timeline</h3>
            <p className="text-xs text-slate-500">Risk progression as speech sentences arrived</p>
          </div>
        </div>

        <div className="h-44 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={timelineData}>
              <XAxis dataKey="time" stroke="#94A3B8" fontSize={11} />
              <YAxis domain={[0, 100]} stroke="#94A3B8" fontSize={11} />
              <Tooltip />
              <Line
                type="monotone"
                dataKey="score"
                stroke={isHighRisk ? '#EF4444' : '#10B981'}
                strokeWidth={3}
                dot={{ r: 4 }}
              />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* TRANSCRIPT INSPECTION */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 space-y-4">
        <h3 className="font-bold text-slate-900 text-base">Full Timestamped Transcript</h3>

        <div className="divide-y divide-slate-100 space-y-3 pt-2">
          {call.transcript.map((seg) => (
            <div
              key={seg.id}
              className={`p-3.5 rounded-xl border transition-colors ${
                seg.isSuspicious
                  ? 'bg-red-50/70 border-red-200'
                  : 'bg-slate-50 border-slate-100'
              }`}
            >
              <div className="flex items-center justify-between text-xs mb-1">
                <span className="font-bold text-slate-900">{seg.speaker}</span>
                <span className="font-mono text-slate-400 text-[11px]">{seg.timestamp}</span>
              </div>
              <p
                className={`text-xs sm:text-sm leading-relaxed ${
                  seg.isSuspicious ? 'text-red-950 font-medium' : 'text-slate-700'
                }`}
              >
                {seg.text}
              </p>
              {seg.detectedSignal && (
                <div className="mt-2 text-xs text-red-800 font-semibold flex items-center space-x-1.5">
                  <ShieldAlert className="w-3.5 h-3.5 text-red-600" />
                  <span>Flagged Signal: {seg.detectedSignal.label}</span>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Delete Confirmation Modal */}
      {confirmDeleteModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-xs">
          <div className="w-full max-w-md bg-white rounded-2xl p-6 shadow-2xl border border-slate-200 space-y-4">
            <h3 className="text-lg font-bold text-slate-900">Delete Forensic Record?</h3>
            <p className="text-xs text-slate-600 leading-relaxed">
              Are you sure you want to remove this call transcript from your local storage? This action cannot be undone.
            </p>
            <div className="flex justify-end space-x-2 pt-2">
              <button
                onClick={() => setConfirmDeleteModal(false)}
                className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-600 hover:text-slate-900"
              >
                Cancel
              </button>
              <button
                onClick={handleDelete}
                className="px-4 py-2 rounded-xl text-xs font-bold bg-red-600 hover:bg-red-700 text-white"
              >
                Permanently Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
